name: Desplegar React en GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usa la versi칩n de Node de tu proyecto
          cache: 'npm'

      # 1. Instala dependencias usando el 'package-lock.json'
      - name: Instalar dependencias
        run: npm ci 

      # 2. Compila la aplicaci칩n de React
      # Usar치 el 'homepage' de tu package.json autom치ticamente
      - name: Build
        run: npm run build

      # 3. Sube el artefacto
      - name: Subir artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # La carpeta de salida de React (CRA) es 'build'
          path: './build' 

  # El 'job' de despliegue no cambia
  deploy:
    needs: build
    permissions:
      pages: write      
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
